### PR TITLE
Some fixes to spanish translation.

### PR DESCRIPTION
**Pull request by marce1994**
I think there are more things to talk about and think, but i think they are ok.

### CODE REVIEW

**Comment by Fazendaaa** [comment]
Good to know that spoiler is used in Spanish too. In Brazilian Portuguese, we have a "legacy" of old words that are translations of its original source material, only after the we "broke" the Portuguese from Portugal making one of our own that we had some freedom to let the things stay as it original way.

And thanks you for fixing this, I really do appreciate :)

**Comment by marce1994** [comment]
@Fazendaaa there are unit test over this?

yup, recently "cablevision flow" released an ad in tv, with principal theme "spoilers" xD.
https://youtu.be/Q-S8LguqCYA

**Comment by Fazendaaa** [comment]
@marce1994, no... I'm this project I only added English tests.

note: I loved this tv ad, thank you for showing it to me hahahahahah

**Comment by marce1994** [comment]
@Fazendaaa i want to build a open source anime web page some day, with some "toys" that i want to try.
i gived it a try with some repos, but i dont have the experience to do it alone yet...
https://github.com/marce1994/ShaReIt-Network

I want to use IPFS, steemit as backend(for content and monetization for 0 ads), and maybe a pet in app... like your anime bot as chibi character with ears  jaja. (maybe dreaming a lot, buy im bored about anime webpages today...)

if you are interested on it, please let me know :)

whanks!

**Comment by Fazendaaa** [comment]
@marce1994, I think that the most import thing your already doing, that what we called -- please forgive me not using English and relying on your comprehension of what I want to mean in Portuguese -- "por a mão na massa".

I did a lot of things in my bots because of the feedback of those who use it. Without this is difficult to understand what you really want to do it; likewise, look what I want [to do](https://github.com/Fazendaaa/AnilistBot#todo) with AnilistBot due to some brainstorms that I had due to user input and requests... Just to know, the first feedback that I had was that some of my countrymen thought that was horrible that I didn't let the user had a "language" option.

Letting "breath" like a wine is the most important thing in a project, talking to those who are interested even more than you sometimes in your project.

I really hope that you keep going strong in your project, anything clue that I might had I will give it to you, any doubt that you had, please contact me here or even in Telegram: @farmy :)

**Comment by marce1994** [comment]
Thanks for the push, ill do this project.
You have a lot of things to do in your app jaja, if there is something "easy" i'll give it a try...

how can i found the bot in telegram? @ what

**Comment by Fazendaaa** [comment]
@marce1994, is @AnilistBot :)

**Pull request merged**
